### PR TITLE
needs a license

### PR DESCRIPTION
**Pull request by jasonkarns**
@chriseppstein Is MIT okay with you? Seems to be the most common in the rbenv ecosystem

### CODE REVIEW

**Comment by mislav** [comment]
I vote for CC0 unless @chriseppstein has a strong preference for MIT.

**Comment by jasonkarns** [comment]
what say you @chriseppstein ?

**Comment by mislav** [comment]
Since rbenv-each is under the rbenv org which I'm primarily responsible for now, I've went ahead and added CC0 to this project. Please holler if someone wishes to discuss that.

**Comment by mislav** [comment]
@jasonkarns Thanks for suggesting that this project needed a license! I've never even noticed.

And thanks for all your numerous contributions to rbenv family of projects!

**Pull request closed without merging**
